name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      GH_URL: https://github.com
      REPO: alan-jino/cosign
    steps:
      - name: Check out GitHub repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKENS }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}
#      - uses: goodwithtech/dockle-action@main
#        with:
#          image: ${{ env.REGISTRY }}/${{ env.REPO }}/app:${{ github.run_id }}
#          format: 'list'
#          exit-code: '1'
#          exit-level: 'warn'
#          ignore: 'CIS-DI-0001,DKL-DI-0006'
      - name: Install cosign
        uses: sigstore/cosign-installer@main
      - name: Sign the images
        run: |
          cosign sign -y ${{ env.REGISTRY }}/${{ env.REPO }}
        env:
          COSIGN_EXPERIMENTAL: 1
      - name: Verify the pushed tags
        run: cosign verify ${{ env.REGISTRY }}/${{ env.REPO }} --certificate-identity ${{ env.GH_URL }}/${{ env.REPO }}/.github/workflows/docker-image.yml --certificate-oidc-issuer https://token.actions.githubusercontent.com
        env:
          COSIGN_EXPERIMENTAL: 1
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GIT_TOKENS }} # or ${{ secrets.github_pat_name }} if you're using a PAT