name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      DH_URL: https://hub.docker.com
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
       DOCKER_USER : ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: docker build
      run:  docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/signed-images
    - name: Docker push
      run : docker push ${{secrets.DOCKER_USER}}/signed-images
    
    - name: Install cosign
      uses: sigstore/cosign-installer@main
    - name: Sign the images
      run: |
          cosign sign -y ${{ env.REGISTRY }}/${{ docker.repository }}/app:${{ env.RELEASE_VERSION }}
      env:
        COSIGN_EXPERIMENTAL: 1
    - name: Verify the pushed tags
      run: cosign verify ${{ env.REGISTRY }}/${{ docker.repository }}/app:${{ env.RELEASE_VERSION }} --certificate-identity ${{ env.DH_URL }}/${{ docker.repository }}/.github/workflows/docker-image.yml@refs/tags/${{ env.RELEASE_VERSION }}  --certificate-oidc-issuer https://token.actions.githubusercontent.com
      env:
        COSIGN_EXPERIMENTAL: 1
            
    