name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      DH_URL: https://hub.docker.com
      RELEASE_VERSION: latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
       DOCKER_USER : ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build image and push to Docker registry
      uses: docker/build-push-action@v4
     
    - name: docker build
      run:  docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/signed-images
    - name: Docker push
      run : docker push ${{secrets.DOCKER_USER}}/signed-images
    
    - name: Install cosign
      uses: sigstore/cosign-installer@v3.1.1
    - name: Regenerate Fulcio Token
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.FULCIO_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}' \
          https://fulcio.sigstore.dev/api/v2/trustBundle
    - name: Sign the images
      run: |
          cosign sign -y  --fulcio-url='https://fulcio.sigstore.dev/api/v2/trustBundle' ${{ env.REGISTRY }}/alanjino/signed-images:${{ env.RELEASE_VERSION }}
      env:
        COSIGN_EXPERIMENTAL: 1
    - name: Verify the pushed tags
      run: cosign verify ${{ env.REGISTRY }}/alanjino/signed-images/:${{ env.RELEASE_VERSION }} --certificate-identity ${{ env.DH_URL }}/alanjino/signed-images/.github/workflows/docker-image.yml@refs/tags/${{ env.RELEASE_VERSION }}  --certificate-oidc-issuer https://fulcio.sigstore.dev/api/v2/trustBundle
      env:
        COSIGN_EXPERIMENTAL: 1
            
    